In [2]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a=np.ones((3,3),dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr [arr%2==1]=-1
arr 

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b=np.where(arr%2==1,-1,arr)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [28]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [30]:
x=np.array([1,5,7,8])

In [31]:
np.repeat(x,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [33]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [38]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index=np.where((a>=5) & (a<=10))
a[index]

array([ 6,  9, 10])

In [39]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [40]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [44]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [46]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [56]:
np.random.uniform(5,10,size=(3,3))

array([[5.27393273, 9.71605543, 9.19992322],
       [5.69308544, 6.89111416, 5.58501344],
       [6.03733295, 6.99268819, 8.73818522]])

In [57]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.017, 0.131, 0.549],
       [0.433, 0.555, 0.198],
       [0.835, 0.921, 0.654],
       [0.991, 0.327, 0.276],
       [0.11 , 0.549, 0.176]])

In [59]:
np.set_printoptions(suppress=False)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
rand_arr

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

In [61]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [70]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

How to convert a 1d array of tuples to a 2d numpy array?

In [72]:
a=np.arange(10)
a

array([0, 1, 2, ..., 7, 8, 9])

In [74]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

28. How to compute the mean, median, standard deviation of a numpy array?

In [75]:
a=np.random.rand(2,2)
a

array([[0.575, 0.891],
       [0.209, 0.185]])

In [76]:
a.mean()

0.4652364063516947

In [79]:
a.std()

0.2904821790878628