FOR NUMPY WEBSITE 50 numpy methods or attribute

In [2]:
import numpy as np

In [3]:
x=np.random.rand(2,2) #1 for ramdom array
x

array([[0.57522096, 0.34851394],
       [0.92467546, 0.8106782 ]])

In [4]:
x.ndim #2 for dimesnsion

2

In [7]:
x.shape #3

(2, 2)

In [8]:
x.size #4

4

In [9]:
type(x) #5

numpy.ndarray

In [10]:
x.dtype #6

dtype('float64')

In [12]:
y=np.array([[1,2,3,4],[5,6,7,8]]) #7
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
z=np.ones((3,4)) #8
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
z=np.zeros((1,2)) #9
z

array([[0., 0.]])

In [19]:
y=np.empty( (1,3) )  #10 
y

array([[4.47593816e-091, 9.79652007e+252, 1.01820481e+277]])

In [33]:
y=np.arange( 10) #11

In [34]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b = np.arange(10,30)   #12
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [36]:
c = np.arange(10,20,3)   #13
c

array([10, 13, 16, 19])

In [40]:
a=np.array( [20,30,40,50] )
b=np.arange(4)

In [41]:
a-b#14

array([20, 29, 38, 47])

In [42]:
a+b #15

array([20, 31, 42, 53])

In [43]:
a-b #16

array([20, 29, 38, 47])

In [44]:
a*b #17

array([  0,  30,  80, 150])

In [45]:
a*20 #18

array([ 400,  600,  800, 1000])

In [46]:
a/10 #19

array([2., 3., 4., 5.])

In [47]:
a-10 #20

array([10, 20, 30, 40])

In [48]:
a+90 #21

array([110, 120, 130, 140])

In [49]:
a**2 #22

array([ 400,  900, 1600, 2500], dtype=int32)

In [50]:
10*np.sin(a) #23

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [51]:
a<2 #24

array([False, False, False, False])

In [52]:
a @ b                 #25      # matrix product

260

In [53]:
a.dot(b) #26

260

In [54]:
a.sum() #27

140

In [55]:
a.min() #28

20

In [56]:
a.max() #29

50

In [57]:
a.sum(axis=0) #30

140

In [59]:
a=np.random.rand(2,3,5)

In [60]:
a.sum(axis=1) #31

array([[1.45258179, 2.09287986, 1.78160773, 0.84642354, 0.93308024],
       [1.38812728, 1.27736127, 1.37918391, 1.60811198, 1.58589883]])

In [63]:
a.cumsum(axis=1)  # cumulative sum along each row #32

array([[[0.20331897, 0.68644356, 0.95708642, 0.01869085, 0.75541383],
        [1.1847155 , 1.46375355, 1.29617807, 0.40002726, 0.75838799],
        [1.45258179, 2.09287986, 1.78160773, 0.84642354, 0.93308024]],

       [[0.75313025, 0.67271007, 0.21889221, 0.64164956, 0.42189207],
        [1.20190836, 0.81867064, 0.74367214, 1.11032483, 0.92107557],
        [1.38812728, 1.27736127, 1.37918391, 1.60811198, 1.58589883]]])

In [64]:
a.cumsum(axis=0) #33

array([[[0.20331897, 0.68644356, 0.95708642, 0.01869085, 0.75541383],
        [0.98139653, 0.77730999, 0.33909165, 0.38133641, 0.00297416],
        [0.26786629, 0.62912631, 0.48542966, 0.44639628, 0.17469226]],

       [[0.95644922, 1.35915363, 1.17597863, 0.66034041, 1.17730589],
        [1.43017464, 0.92327056, 0.86387158, 0.85001168, 0.50215766],
        [0.45408521, 1.08781694, 1.12094144, 0.94418343, 0.83951551]]])

In [71]:
a=np.array([1,3,2])
b=np.array([2,6,7])
a

array([1, 3, 2])

In [67]:
np.exp(a) #34

array([ 2.71828183, 20.08553692,  7.3890561 ])

In [68]:
np.exp2(a) #35

array([2., 8., 4.])

In [69]:
np.sqrt(a) #36

array([1.        , 1.73205081, 1.41421356])

In [72]:
np.add(a,b) #37

array([3, 9, 9])

In [73]:
np.multiply(a,b) #38

array([ 2, 18, 14])

In [74]:
np.divide(a,b) #39

array([0.5       , 0.5       , 0.28571429])

In [76]:
a = np.arange(10)**3 #40
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [77]:
a[2] #41

8

In [78]:
a[2:5] #42

array([ 8, 27, 64], dtype=int32)

In [79]:
a[:6:2] = 1000 #43

In [80]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [81]:
a[ : :-1]                                 # reversed a #44

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [91]:
a=np.random.rand(3,2)

In [94]:
a

array([[0.97757693, 0.78957082],
       [0.64887956, 0.80583401],
       [0.66817426, 0.98581341]])

In [95]:
a[1,1] #45

0.8058340081170428

In [96]:
a[0:2,1] # each row in the second column of b #46

array([0.78957082, 0.80583401])

In [97]:
a[:,1]  # equivalent to the previous example #47

array([0.78957082, 0.80583401, 0.98581341])

In [98]:
a[1:2,1]  # each column in the second and third row of b #48

array([0.80583401])

In [99]:
a[-1]  # the last row. Equivalent to b[-1,:] #49

array([0.66817426, 0.98581341])

In [100]:
a=np.random.rand(3,2,2)

In [101]:
a[1,1,1] #3D #50

0.5831032842053989